# mkdocs.yml
site_name: Psymple Docs

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: false

nav:
  - Introduction: index.md
  - Overview:
    - systems.md
    - symbolic_systems.md
  - Tutorials: tutorials.md
  - Modelling Components:
    - Differential Equations: components/differential_equations.md
  - Reference:
    - Assignments: assignments.md